---
title: Containerising an R Shiny Application - lite version
subtitle: Part of the "Self Hosted" Series
---

### Why redo the R Shiny example with an alpine image

size of rshiny image: 544.9 MB

size of alpine image: about 140 MB (+ my own shiny installation...)

Much more lightweight and fast. 

### R Shiny locally

In case you haven't gotten around to using R shiny locally, I encourage you to try to run your simple shiny application locally, before containerising it. 

To do this, you could follow the [minimal example in the R Shinydocumentation](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/)

Or, you could try to run this app locally.

To do this, you should do the following:

#### create an `/app` folder and within that folder, the following 2 files

`ui.R`:
```r
ui <- fluidPage(
    titlePanel("Mini Survey"),

    mainPanel(
        selectInput("satisfaction", "How satisfied are you?",
                    choices = c("Very satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very dissatisfied")),
        actionButton("submit", "Submit"),
        hr(),
        textOutput("thanks")
    )
) 
```

`server.R`:

```r
library(shiny)
library(DBI)
library(RPostgres)

connect_to_db <- function() {
  dbConnect(
    RPostgres::Postgres(),
    host = Sys.getenv("PG_HOST", "postgres"),
    user = Sys.getenv("PG_USER", "postgres"),
    password = Sys.getenv("PG_PASSWORD", "postgres"),
    dbname = Sys.getenv("PG_DB", "testdb"),
    port = 5432
  )
}


server <- function(input, output, session) {

  output$result <- renderPrint({
    con <- connect_to_db()
    on.exit(dbDisconnect(con))

    dbGetQuery(con, "SELECT NOW() AS server_time;")
  })
}

```

#### run app!

make sure your working directory is set to your `/app` directory, then run:

```r
shiny::runApp()
```


### R shiny containerized

To do this, we can use the skeleton of the R Shiny local app, and just have to add a dockerfile, and a docker compose file, not in the `/app` directory.

```dockerfile
FROM devxygmbh/r-alpine:4-3.21

# Install OS deps needed for Postgres + Shiny
RUN apk add --no-cache \
      postgresql-client \
      postgresql-libs \
      postgresql-dev \
      g++ \
      make \
      libc6-compat \
      curl \
      # chat want's me to install these in case system libs are lacking to build shiny
      openssl-dev \
      zlib-dev \
      libuv-dev \
      postgresql-client postgresql-libs postgresql-dev


# Install R packages (Shiny + Postgres)
RUN R -q -e "install.packages(c('shiny','DBI','RPostgres'), repos='https://cloud.r-project.org')"

# Copy app
WORKDIR /app
COPY app ./app

EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('app', host='0.0.0.0', port=3838)"]
```

```yaml
services:
  postgres:
    # a name, e.g.,  db_container is instrumental to be
    # called as host from the shiny app
    image: postgres
    container_name: db_container
    # build: ./postgres
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    # This port mapping is only necessary to connect from the host, 
    # not to let containers talk to each other. 
    # port-forwarding: von host port:nach docker port -> mapping 
    ports:
        - "1111:5432"
    # if container killed, then data is still stored in volume (locally)
    volumes:
        - "/var/lib/postgresql"

    # do i need this additional shiny installation
  shiny:
    build: .
    container_name: shiny_app
    depends_on:
      - postgres
    ports:
      - "3838:3838"
    environment:
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: testdb

```
With this, we can now try running our R shiny application within our container. 

For this, we first have to install Docker Desktop, but I am assuming you have already gone through Matt's first blog post, so you've done this.

Next, you make sure your docker daemon is running, by opening docker desktop, and then in the directory of this example, run the following 

```bash
docker-compose build
```

```bash
docker-compose up
```