# Base image
FROM devxygmbh/r-alpine:4-3.21

# Install system dependencies (Alpine package manager)
RUN apk update && apk add --no-cache \
    libpq \
    libxml2 \
    libcurl \
    libgit2 \
    postgresql-client \
    postgresql-libs \
    build-base \
    postgresql-dev \
    libxml2-dev \
    libcurl-dev \
    libgit2-dev
    # potentially
#     g++ \
#       make \
#       libc6-compat \
#       curl \
#       # chat want's me to install these in case system libs are lacking to build shiny
#       openssl-dev \
#       zlib-dev \
#       libuv-dev \

# Install R packages
RUN R -q -e 'install.packages(c("shiny", "RPostgres", "shinythemes", "shinyjs", "DBI"), repos="https://cloud.r-project.org")'

EXPOSE 3838

# not actually used, overwritten by `docker-compose.yml`, here just in case the container is used alone, without docker-compose.
CMD ["R", "-e", "shiny::runApp('/srv/shiny-server/survey', host='0.0.0.0', port=3838)"]